version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build-and-test:
    macos:
      xcode: 11.3.1
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run: cd Example && bundle exec pod install
      - run: xcodebuild -workspace ./Example/FuzzyMatchingSwift.xcworkspace -scheme FuzzyMatchingSwift-Example -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -enableCodeCoverage YES clean test | xcpretty -c --report junit --output junit.xml
      - run: xcodebuild -workspace ./Example/FuzzyMatchingSwift.xcworkspace -scheme FuzzyMatchingSwift-iOS CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build | xcpretty -c
      - run: xcodebuild -workspace ./Example/FuzzyMatchingSwift.xcworkspace -scheme FuzzyMatchingSwift-macOS clean build | xcpretty -c
      - run: xcodebuild -workspace ./Example/FuzzyMatchingSwift.xcworkspace -scheme FuzzyMatchingSwift-watchOS -destination "generic/platform=watchOS" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" clean build | xcpretty -c
      - run: xcodebuild -workspace ./Example/FuzzyMatchingSwift.xcworkspace -scheme FuzzyMatchingSwift-tvOS -destination "platform=tvOS Simulator,name=Apple TV 4K (at 1080p)" clean build | xcpretty -c
      - run: bundle exec pod lib lint --quick --allow-warnings
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --config .swiftlint.yml --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
      - swiftlint